name: Build P2 node Project
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  release-project:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-project
    steps:
    - name: Download artifact/site
      uses: actions/download-artifact@v3
      with:
        name: site
    - name: View content of artifact
      run: ls -R
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: npm install
    - name: Build Project assets
      run: npm run build
    - name: Upload static content
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: .next/
      
      
      # macOS Monterey 12	macos-latest or macos-12	The macos-latest label currently uses the macOS 12 runner image.
      # macOS Big Sur 11	macos-11
